name: EterniaKamui
main: br.com.eterniaserver.eterniakamui.EterniaKamui
softdepend: [Vault, WorldGuard, WorldEdit, EterniaServer]
dev-url: https://github.com/EterniaServer/EterniaKamui
depend: [EterniaLib]
version: '${project.version}-${git.commit.id.abbrev}'
api-version: '1.16'