package br.com.eterniaserver.eterniakamui.enums;

public enum Booleans {

    PISTON_EXPLOSION_SOUND,
    CREATIVE_WORLD_EXIST,

    CLAIMS_PREVENT_GLOBAL_MONSTER_EGGS,
    CLAIMS_PREVENT_THEFT,
    CLAIMS_PROTECT_CREATURES,
    CLAIMS_PROTECT_HORSES,
    CLAIMS_PROTECT_DONKEYS,
    CLAIMS_PROTECT_LLAMAS,
    CLAIMS_PREVENT_BUTTONS_SWITCHES,
    CLAIMS_LOCK_WOODEN_DOORS,
    CLAIMS_LOCK_TRAP_DOORS,
    CLAIMS_LOCK_FENCE_GATES,
    CLAIMS_ENDERPEARLS_REQUIRE_ACCESSTRUST,
    CLAIMS_RAID_TRIGGERS_REQUIRE_BUILDTRUST,
    CLAIMS_RESPECT_WORLDGUARD,
    CLAIMS_VILLAGER_TRADING_REQUIRES_TRUST

}
