package br.com.eterniaserver.eterniakamui.enums;

public enum Integers {

    CLAIMS_MAX_CLAIMS_PER_PLAYER,
    CLAIMS_INITIAL_BLOCKS,
    CLAIMS_BLOCKS_ACCRUED_PER_HOUR,
    CLAIMS_MAX_ACCRUED_BLOCKS,
    CLAIMS_ACCRUED_IDLE_THRESHOLD,
    CLAIMS_ACCRUED_IDLE_PERCENT,
    CLAIMS_EXPIRATION_DAYS,
    CLAIMS_AUTOMATIC_CLAIMS_FOR_NEW_PLAYERS_RADIUS,
    CLAIMS_MIN_WIDTH,
    CLAIMS_MIN_AREA

}
